"""
Local-only admin tool for dudus-app (issue #31, scoped in #15).

Adds a new card to src/data/card_index.json (with an optional photo) and lets an existing
card's photo be added, replaced, or removed. Never deployed — lives outside the Next.js build
(nothing under tools/ is imported by the app or referenced by next.config.ts), reachable only by
running it locally. Each action publishes itself to the live site automatically (issue #34): a
throwaway git worktree (never the live working directory a running instance of this tool might
be serving out of) carries the change through a real branch -> PR -> e2e -> squash-merge cycle,
skipping the VERSION/CHANGELOG/tag ceremony and per-change issue that a code change would need,
since this is content, not a release — see ONBOARDING.md's "Automated content publishing" note.

Run from the repo root:
    conda run -n ds streamlit run tools/dudu-intake/app.py
"""

import io
import json
import re
import shutil
import subprocess
import tempfile
import time
import uuid
from collections import Counter
from pathlib import Path

import fitz
import streamlit as st
from PIL import Image, ImageOps

try:
    import tkinter as tk
    from tkinter import filedialog

    TKINTER_AVAILABLE = True
except ImportError:
    TKINTER_AVAILABLE = False

REPO_ROOT = Path(__file__).resolve().parents[2]
CARD_INDEX_PATH = REPO_ROOT / "src" / "data" / "card_index.json"
PHOTOS_DIR = REPO_ROOT / "public" / "photos"
DUDUS_ROOT = REPO_ROOT.parent / "Dudus"

GITHUB_REPO = "ericgitonga/dudus-app"
CI_POLL_INTERVAL_SECONDS = 8
CI_POLL_TIMEOUT_SECONDS = 600

CARD_KEY_ORDER = [
    "id",
    "common_name",
    "scientific_name",
    "family",
    "order",
    "taxon_rank",
    "sourcing",
    "sections",
    "technical_sections",
    "source_report_ref",
    "photo_ref",
    "reviewed_by",
    "reviewed_at",
]

IMAGE_SUFFIXES = (".jpg", ".jpeg", ".png")

# These three have no edit UI yet (only photos do) — left as clearly-a-placeholder values for a
# human to fill in by hand later, not guessed at.
DEFAULT_TAXON_RANK = "species"
DEFAULT_SOURCING = ""

ORDER_UNKNOWN_LABEL = "Unknown (fix later)"
ORDER_OTHER_LABEL = "Other (type manually)"

TARGET_RATIO = 3 / 2
RATIO_TOLERANCE = 0.02

# Font sizes below come from md_to_pdf_rl.py's H1/H2 ParagraphStyles (20pt / 15pt, both bold) —
# the same converter that produced every existing lay report. A generous floor (18/12) tolerates
# minor font-substitution drift without needing exact pt matches.
TITLE_MIN_SIZE = 18
HEADING_MIN_SIZE = 12


def load_cards():
    with open(CARD_INDEX_PATH) as f:
        return json.load(f)


def serialize_cards(cards):
    return (json.dumps(cards, indent=2, ensure_ascii=False) + "\n").encode()


def save_cards(cards):
    with open(CARD_INDEX_PATH, "wb") as f:
        f.write(serialize_cards(cards))


def slugify(text):
    slug = re.sub(r"[^a-z0-9]+", "-", text.strip().lower())
    return slug.strip("-")


def parse_report_pdf(pdf_bytes):
    """
    Extract (title, sections, error) from a report PDF generated by md_to_pdf_rl.py — works for
    either the lay-audience report or the technical report, since both share the same H1/H2
    convention. The title is the report's own H1 (the common name, as authored) — possibly
    wrapped across several visual lines, which get joined with a space; every subsequent bold
    heading starts a new section, with regular-weight text collected as that section's body
    until the next heading. Returns error=None on success, or a human-readable reason parsing
    failed.
    """
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    lines = []
    for page in doc:
        for block in page.get_text("dict")["blocks"]:
            for line in block.get("lines", []):
                spans = line["spans"]
                text = "".join(s["text"] for s in spans).strip()
                if not text:
                    continue
                size = max(s["size"] for s in spans)
                bold = any("Bold" in s["font"] for s in spans)
                lines.append((text, size, bold))

    title = None
    sections = []
    current = None
    for text, size, bold in lines:
        # A wrapped H1 renders as several consecutive lines at title size, all before any
        # section has started — join them rather than mis-filing the wrapped remainder as a
        # bogus first section (#76).
        if current is None and bold and size >= TITLE_MIN_SIZE:
            title = text if title is None else f"{title} {text}"
            continue
        if bold and size >= HEADING_MIN_SIZE:
            current = {"heading": text, "body": []}
            sections.append(current)
            continue
        if current is not None:
            current["body"].append(text)

    if title is None:
        return None, [], "Couldn't find a title (no large bold heading) — is this the right PDF?"
    if not sections:
        return title, [], "Found a title but no section headings — is this the lay report, not the technical one?"

    # Some reports phrase the title as a sentence ("The White-Ringed Atlas Moth") rather than a
    # bare name — no existing common_name in card_index.json starts with an article, so this is
    # always noise to drop, never a legitimate part of the name.
    title = re.sub(r"^(the|an?)\s+", "", title, flags=re.IGNORECASE)

    return title, [{"heading": s["heading"], "body": " ".join(s["body"])} for s in sections], None


def find_technical_pdf_path(common_name, lay_filename):
    """Look for the sibling technical PDF (same name minus "-la") in Dudus/<common_name>/, per
    the naming convention every existing report follows. None if this machine has no Dudus/
    checkout or no match is found."""
    technical_filename = lay_filename.replace("-la.pdf", ".pdf")
    if technical_filename == lay_filename:
        return None
    candidate = DUDUS_ROOT / common_name / technical_filename
    return candidate if candidate.exists() else None


def find_technical_ref(common_name, lay_filename):
    """String form of find_technical_pdf_path for source_report_ref — empty string (not None,
    the schema doesn't allow null here) if there's no match."""
    path = find_technical_pdf_path(common_name, lay_filename)
    return f"{common_name}/{path.name}" if path else ""


def technical_filename_for(lay_filename):
    """The sibling technical filename for a given lay-report filename, per the naming convention
    every existing report follows (same name minus "-la"). None if `lay_filename` doesn't end in
    "-la.pdf" (so has no technical sibling to derive)."""
    technical_filename = lay_filename.replace("-la.pdf", ".pdf")
    return None if technical_filename == lay_filename else technical_filename


def scan_species_directory(dir_path):
    """
    Classify the PDFs and images sitting directly inside `dir_path` (a species folder such as
    `Dudus/<CommonName>/`) for the directory-based add flow (#89): every `*-la.pdf` is a lay
    report candidate, paired with its technical sibling via technical_filename_for(); every
    image file (jpg/jpeg/png) is a photo candidate. Returns a dict:
      {"pairs": [(lay_path, technical_path_or_None), ...], "photos": [photo_path, ...]}
    Both lists are sorted by filename for a stable, predictable UI order. `technical_path` is
    None when the lay report's sibling technical file isn't actually present in the directory
    (a card can still be added — the technical link just won't be there until it is).
    """
    lay_paths = sorted(p for p in dir_path.iterdir() if p.name.lower().endswith("-la.pdf"))
    pairs = []
    for lay_path in lay_paths:
        technical_name = technical_filename_for(lay_path.name)
        technical_path = dir_path / technical_name if technical_name else None
        if technical_path is not None and not technical_path.exists():
            technical_path = None
        pairs.append((lay_path, technical_path))

    photos = sorted(
        p for p in dir_path.iterdir() if p.suffix.lower() in IMAGE_SUFFIXES
    )
    return {"pairs": pairs, "photos": photos}


def resolve_species_directory(raw_input):
    """Resolve a user-typed directory string against DUDUS_ROOT (relative) or as an absolute
    path, whichever exists. Returns (Path, error_message) — error_message is None on success."""
    raw = raw_input.strip()
    if not raw:
        return None, "Enter a directory first."
    candidate = Path(raw)
    if not candidate.is_absolute():
        candidate = DUDUS_ROOT / raw
    if not candidate.is_dir():
        return None, f"Not a directory: {candidate}"
    return candidate, None


def browse_for_species_directory():
    """Open the OS's native folder picker, rooted at DUDUS_ROOT — safe to shell out to tkinter
    here since this tool is local-only, always launched and viewed on the admin's own machine
    (never a remote server), per README. Returns the chosen path relative to DUDUS_ROOT when
    it's inside it (so it round-trips through resolve_species_directory like a typed relative
    path), the absolute path otherwise, or None if unavailable or cancelled."""
    if not TKINTER_AVAILABLE:
        return None
    root = tk.Tk()
    root.withdraw()
    root.attributes("-topmost", True)
    try:
        chosen = filedialog.askdirectory(
            initialdir=str(DUDUS_ROOT) if DUDUS_ROOT.is_dir() else str(Path.home()),
            title="Select species directory",
            parent=root,
        )
    finally:
        root.destroy()
    if not chosen:
        return None
    chosen_path = Path(chosen)
    try:
        return str(chosen_path.relative_to(DUDUS_ROOT))
    except ValueError:
        return str(chosen_path)


def guess_order_from_technical(technical_path):
    """
    Every technical report states the taxonomic order in prose during its "Taxonomy and
    Classification" section (e.g. "Order Hemiptera", "belong to Order Araneae") — consistent
    enough across the corpus to regex for, though it's a heuristic over free text, not a
    structured field. Returns the most common match, or None if the file is missing or the
    pattern isn't found (caller falls back to manual entry either way).
    """
    if not technical_path:
        return None
    doc = fitz.open(str(technical_path))
    text = "\n".join(page.get_text() for page in doc)
    matches = re.findall(r"\bOrder\s+([A-Z][a-zA-Z]+)\b", text)
    if not matches:
        return None
    return Counter(matches).most_common(1)[0][0]


def order_card(card):
    return {k: card.get(k) for k in CARD_KEY_ORDER}


def normalize_photo(img):
    """
    Strip EXIF/GPS metadata and bake in orientation, mirroring stripPhotoMetadata.ts (#10) so
    a photo gets the same treatment regardless of where it came from (an admin upload or one
    extracted straight out of a report PDF, #83). Then apply the pad-to-3:2 convention from
    SKILL.md: only pads (never crops) since "crop tight to the dudu" is a manual judgment call
    the tool can't make. Returns (image, warning | None).
    """
    img = ImageOps.exif_transpose(img)
    img = img.convert("RGB")

    w, h = img.size
    ratio = w / h
    warning = None

    if ratio < TARGET_RATIO - RATIO_TOLERANCE:
        target_w = round(h * TARGET_RATIO)
        padded = Image.new("RGB", (target_w, h), "white")
        padded.paste(img, ((target_w - w) // 2, 0))
        img = padded
    elif ratio > TARGET_RATIO + RATIO_TOLERANCE:
        warning = (
            f"This photo is wider than 3:2 ({w}x{h}). The tool only pads narrow photos — "
            "it won't crop into the subject automatically. Crop it tighter yourself first "
            "(see SKILL.md's photo convention), or upload as-is and expect some edge crop "
            "on the site's 3:2/4:3 views."
        )

    return img, warning


def process_photo(uploaded_file):
    """Load an admin-uploaded photo file and normalize it — see normalize_photo()."""
    return normalize_photo(Image.open(uploaded_file))


def extract_embedded_photo(pdf_bytes):
    """
    Pull the specimen photo out of a report PDF, if one is embedded (per SKILL.md's Photo line
    convention — `![](<filename>)` placed right under the taxonomy line). Used so an admin
    doesn't have to re-upload a photo that's already sitting in the PDF they just gave the tool
    (#83). Picks the largest embedded raster image by pixel area across the whole document,
    since that's reliably the specimen photo rather than some incidental artifact. Returns
    (PIL.Image, ext) — ext is "png" or "jpg" — or (None, None) if the PDF embeds no raster image
    at all.
    """
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    best = None  # (area, xref)
    for page in doc:
        for xref, _smask, width, height, *_rest in page.get_images(full=True):
            area = width * height
            if best is None or area > best[0]:
                best = (area, xref)
    if best is None:
        return None, None

    base = doc.extract_image(best[1])
    img = Image.open(io.BytesIO(base["image"]))
    ext = "png" if base["ext"] == "png" else "jpg"
    return img, ext


def save_photo(img, card_id, ext):
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{card_id}.{ext}"
    fmt = "PNG" if ext == "png" else "JPEG"
    img.save(PHOTOS_DIR / filename, fmt)
    return f"/photos/{filename}"


def delete_photo(photo_ref):
    if not photo_ref:
        return
    path = REPO_ROOT / "public" / photo_ref.lstrip("/")
    if path.exists():
        path.unlink()


def run_cmd(args, cwd, check=True):
    result = subprocess.run(args, cwd=str(cwd), capture_output=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(
            f"`{' '.join(args)}` failed (exit {result.returncode}):\n{result.stdout}\n{result.stderr}"
        )
    return result.stdout.strip()


def publish_content_change(files, commit_message, pr_title, pr_body, log):
    """
    Drive the existing branch -> PR -> e2e -> squash-merge pipeline for a content-only change,
    so using this tool actually publishes to the live site (#34) without VERSION/CHANGELOG/tag
    ceremony or a per-change issue — same reasoning as career-transition's per-client CV/plan
    exemption from issue-first (this is content, not a codebase change).

    `files` maps repo-relative paths to new bytes, or None to delete that path. Runs entirely in
    a throwaway git worktree on its own branch — never checks out anything in REPO_ROOT itself,
    so a concurrently-running instance of this same tool (or an admin's own unrelated local
    edits) in the live working directory is never disturbed.

    Returns (published: bool, pr_url: str | None, detail: str).
    """
    branch = f"intake/{uuid.uuid4().hex[:10]}"
    worktree_dir = Path(tempfile.mkdtemp(prefix="dudu-intake-publish-"))
    pr_url = None
    try:
        log("Fetching latest `main`…")
        run_cmd(["git", "fetch", "origin", "main"], REPO_ROOT)

        log(f"Preparing an isolated worktree on `{branch}`…")
        run_cmd(["git", "worktree", "add", "-b", branch, str(worktree_dir), "origin/main"], REPO_ROOT)

        for rel_path, content in files.items():
            dest = worktree_dir / rel_path
            if content is None:
                if dest.exists():
                    dest.unlink()
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(content)
            run_cmd(["git", "add", "--", rel_path], worktree_dir)

        run_cmd(["git", "commit", "-m", commit_message], worktree_dir)

        log("Pushing…")
        run_cmd(["git", "push", "-u", "origin", branch], worktree_dir)

        log("Opening PR…")
        pr_url = run_cmd(
            [
                "gh", "pr", "create", "--repo", GITHUB_REPO,
                "--title", pr_title, "--body", pr_body, "--head", branch,
            ],
            worktree_dir,
        )
        pr_number = pr_url.rstrip("/").split("/")[-1]

        log(f"PR {pr_url} opened — waiting for checks…")
        deadline = time.time() + CI_POLL_TIMEOUT_SECONDS
        checks = []
        while time.time() < deadline:
            checks_raw = run_cmd(
                ["gh", "pr", "checks", pr_number, "--repo", GITHUB_REPO, "--json", "name,bucket"],
                worktree_dir,
                check=False,
            )
            checks = json.loads(checks_raw) if checks_raw else []
            if checks and all(c["bucket"] != "pending" for c in checks):
                break
            time.sleep(CI_POLL_INTERVAL_SECONDS)
        else:
            return False, pr_url, "Timed out waiting for checks — PR left open for manual review."

        failed = [c["name"] for c in checks if c["bucket"] not in ("pass", "skipping")]
        if failed:
            return False, pr_url, f"Checks failed ({', '.join(failed)}) — PR left open, not merged."

        log("Checks green — merging…")
        run_cmd(
            ["gh", "pr", "merge", pr_number, "--repo", GITHUB_REPO, "--squash", "--delete-branch"],
            worktree_dir,
        )
        return True, pr_url, "Published to the live site."
    finally:
        log("Cleaning up the temporary worktree…")
        run_cmd(["git", "worktree", "remove", "--force", str(worktree_dir)], REPO_ROOT, check=False)
        shutil.rmtree(worktree_dir, ignore_errors=True)
        # Best-effort: if this succeeded, the live working directory's own copy of these files
        # already matches what was just merged (we published its exact current bytes), so this
        # is just bookkeeping to mark it clean — never something to block or error the UI on. Only
        # when REPO_ROOT is actually on `main` — if it's sitting on some other branch (e.g. a dev
        # session working on the tool itself), silently pulling there would be exactly the kind
        # of surprise branch-state change this worktree approach exists to avoid.
        current_branch = run_cmd(["git", "branch", "--show-current"], REPO_ROOT, check=False)
        if current_branch == "main":
            run_cmd(["git", "pull", "--ff-only"], REPO_ROOT, check=False)


def revert_local_files(paths):
    """
    Best-effort: put each path back to its last-committed (HEAD) state — restores a
    deleted/modified tracked file, removes an untracked new one. Used whenever a publish fails,
    so the local working tree never drifts ahead of `main` with content nothing else knows
    about — the next action (single or batch) always starts from a clean, HEAD-matching base.
    """
    for rel_path in paths:
        full = REPO_ROOT / rel_path
        tracked = subprocess.run(
            ["git", "ls-files", "--error-unmatch", rel_path],
            cwd=REPO_ROOT, capture_output=True, text=True,
        ).returncode == 0
        if tracked:
            run_cmd(["git", "checkout", "HEAD", "--", rel_path], REPO_ROOT, check=False)
        elif full.exists():
            full.unlink()


def do_publish(files, commit_message, pr_title, pr_body):
    with st.status("Publishing to the live site…", expanded=True) as status:
        try:
            published, pr_url, detail = publish_content_change(
                files, commit_message, pr_title, pr_body, status.write
            )
        except Exception as e:
            status.update(label="Publish failed", state="error")
            st.error(f"Publish failed: {e}")
            revert_local_files(files.keys())
            return False
        status.update(
            label="Published" if published else "Not published",
            state="complete" if published else "error",
        )
        (st.success if published else st.warning)(f"{detail}\n\n{pr_url}" if pr_url else detail)
        if not published:
            revert_local_files(files.keys())
        return published


def resolve_order_default_index(known_orders, detected_order):
    """
    The index-resolution half of `order_picker`, pulled out as a pure function so it's testable
    without a Streamlit widget context: exactly `known_orders.index(detected_order)` when
    `detected_order` is already a known order, the "Other (type manually)" slot when it's a
    detected-but-new order, or the "Unknown" slot when nothing was detected at all.
    """
    if detected_order and detected_order in known_orders:
        return known_orders.index(detected_order)
    elif detected_order:
        return len(known_orders) + 1  # ORDER_OTHER_LABEL
    else:
        return len(known_orders)  # ORDER_UNKNOWN_LABEL


def order_picker(key_prefix, known_orders, detected_order):
    """
    Selectbox over orders already in use, plus "Unknown" and a manual write-in — because a
    genuinely new order (like Phasmatodea for the first stick insect card) won't be in
    `known_orders` yet, and a dropdown alone can't offer something not already in the data.
    Pre-selects `detected_order` (from guess_order_from_technical) when there is one: exactly if
    it's already a known order, or pre-fills the write-in field with it otherwise so the admin
    only has to confirm, not retype.
    """
    options = known_orders + [ORDER_UNKNOWN_LABEL, ORDER_OTHER_LABEL]
    default_index = resolve_order_default_index(known_orders, detected_order)

    # Keyed on detected_order too, not just key_prefix: st.selectbox only honours a fresh
    # `index=` the first time a given key renders — a new PDF upload landing on the *same* key
    # (e.g. detected_order going from None to "Phasmatodea") would otherwise keep showing
    # whatever the first render defaulted to, same class of bug fixed earlier for text_input.
    choice = st.selectbox(
        "Order", options, index=default_index, key=f"{key_prefix}_order_select_{detected_order}"
    )
    if detected_order and choice == ORDER_OTHER_LABEL:
        st.caption(f"Detected from the technical report: `{detected_order}`")
    if choice == ORDER_OTHER_LABEL:
        manual = st.text_input(
            "Order (manual entry)",
            value=detected_order or "",
            key=f"{key_prefix}_order_manual_{detected_order}",
        )
        return manual.strip() or None
    if choice == ORDER_UNKNOWN_LABEL:
        return None
    return choice


st.set_page_config(page_title="dudus-app intake", layout="wide")
st.title("dudus-app admin intake")
st.caption(
    "Local-only authoring tool — for entering already-researched content (via /dudus or "
    "/dudusonline), not for researching a species itself."
)

st.header("Card Processing")
st.caption(
    "Adding, updating, and deleting cards all happen here. Adding is batch-only — "
    "there is no single-card add form."
)

if "batch_message" in st.session_state:
    st.success(st.session_state.pop("batch_message"))
if "existing_card_message" in st.session_state:
    st.success(st.session_state.pop("existing_card_message"))

st.session_state.setdefault("pending_species_dirs", [])
st.session_state.setdefault("species_dir_input_version", 0)

st.subheader("Add cards")
st.caption(
    "The whole batch publishes as a single PR — one CI run instead of one per card, at the "
    "cost that a single failed check blocks every card in the batch together, not just the "
    "one that broke something."
)
batch_cards_now = load_cards()
known_orders_batch = sorted({c["order"] for c in batch_cards_now if c["order"]})

if TKINTER_AVAILABLE:
    dir_input_col, browse_col, dir_button_col = st.columns([4, 1, 1])
else:
    dir_input_col, dir_button_col = st.columns([5, 1])
    browse_col = None
with dir_input_col:
    dir_input = st.text_input(
        "Species directory (relative to Dudus/, or an absolute path)",
        key=f"species_dir_input_{st.session_state.species_dir_input_version}",
    )
browse_clicked = False
if browse_col is not None:
    with browse_col:
        st.write("")
        browse_clicked = st.button(
            "Browse…", icon=":material/folder_open:", key="browse_species_dir_button"
        )
with dir_button_col:
    st.write("")
    add_dir_clicked = st.button("Add to batch")

if browse_clicked:
    try:
        browsed_dir = browse_for_species_directory()
    except Exception as exc:
        browsed_dir = None
        st.error(f"Couldn't open a folder picker ({exc}) — type the path instead.")
    if browsed_dir:
        st.session_state.species_dir_input_version += 1
        st.session_state[f"species_dir_input_{st.session_state.species_dir_input_version}"] = (
            browsed_dir
        )
        st.rerun()

if add_dir_clicked:
    resolved_dir, dir_err = resolve_species_directory(dir_input)
    if dir_err:
        st.error(dir_err)
    elif str(resolved_dir) in st.session_state.pending_species_dirs:
        st.warning(f"'{resolved_dir}' is already in the batch.")
    else:
        st.session_state.pending_species_dirs.append(str(resolved_dir))
        st.session_state.species_dir_input_version += 1
        st.rerun()

batch_rows = []
seen_ids_this_batch = set()
for dir_i, dir_str in enumerate(st.session_state.pending_species_dirs):
    dir_path = Path(dir_str)
    with st.container(border=True):
        st.write(f"**{dir_path}**")
        if st.button("Remove", key=f"remove_dir_{dir_i}"):
            st.session_state.pending_species_dirs.pop(dir_i)
            st.rerun()

        if not dir_path.is_dir():
            st.error("Directory no longer exists.")
            batch_rows.append({"error": "missing directory"})
            continue

        scanned = scan_species_directory(dir_path)
        if not scanned["pairs"]:
            st.error("No lay report (*-la.pdf) found in this directory.")
            batch_rows.append({"error": "no lay report found"})
            continue

        if len(scanned["pairs"]) == 1:
            lay_path, technical_path = scanned["pairs"][0]
        else:
            pair_labels = [lp.name for lp, _tp in scanned["pairs"]]
            chosen_label = st.selectbox(
                "Which report pair for this card?", pair_labels, key=f"pair_select_{dir_i}"
            )
            lay_path, technical_path = scanned["pairs"][pair_labels.index(chosen_label)]

        lay_bytes = lay_path.read_bytes()
        title, sections, parse_err = parse_report_pdf(lay_bytes)
        if parse_err:
            st.error(parse_err)
            batch_rows.append({"error": parse_err})
            continue

        technical_sections = []
        if technical_path is not None:
            _tech_title, technical_sections, tech_err = parse_report_pdf(
                technical_path.read_bytes()
            )
            if tech_err:
                st.warning(
                    f"Technical report didn't parse ({tech_err}) — card will publish "
                    "without a technical-report link."
                )
                technical_sections = []
        else:
            st.warning(
                "No technical report sibling found — card will publish without a "
                "technical-report link."
            )

        card_id = slugify(title)
        dup_err = None
        if any(c["id"] == card_id for c in batch_cards_now):
            dup_err = f"id '{card_id}' already exists on the live site."
        elif card_id in seen_ids_this_batch:
            dup_err = f"id '{card_id}' is duplicated within this batch."
        seen_ids_this_batch.add(card_id)

        st.caption(
            f"Parsed '{title}' — {len(sections)} lay section(s), "
            f"{len(technical_sections)} technical section(s)."
        )
        if dup_err:
            st.error(dup_err)

        col_a, col_b = st.columns(2)
        with col_a:
            detected_order = guess_order_from_technical(technical_path)
            resolved_order = order_picker(f"batch_{dir_i}", known_orders_batch, detected_order)
        with col_b:
            photo_result = None
            photo_candidates = scanned["photos"]
            if len(photo_candidates) >= 1:
                if len(photo_candidates) == 1:
                    photo_path = photo_candidates[0]
                else:
                    photo_labels = [p.name for p in photo_candidates]
                    chosen_photo_label = st.selectbox(
                        "Which photo?", photo_labels, key=f"photo_select_{dir_i}"
                    )
                    photo_path = photo_candidates[photo_labels.index(chosen_photo_label)]
                preview, warn = normalize_photo(Image.open(photo_path))
                st.image(preview, caption=f"Photo: {photo_path.name}", width=250)
                if warn:
                    st.warning(warn)
                photo_result = (preview, "png" if photo_path.suffix.lower() == ".png" else "jpg")
            else:
                embedded_img, embedded_ext = extract_embedded_photo(lay_bytes)
                if embedded_img is not None:
                    preview, warn = normalize_photo(embedded_img)
                    st.image(preview, caption="Photo embedded in report — used automatically", width=250)
                    if warn:
                        st.warning(warn)
                    photo_result = (preview, embedded_ext)
                else:
                    photo_file = st.file_uploader(
                        "Photo — none found in the directory or embedded in the report",
                        type=["jpg", "jpeg", "png"],
                        key=f"batch_photo_{dir_i}",
                    )
                    if photo_file is not None:
                        preview, warn = process_photo(photo_file)
                        st.image(preview, caption="After metadata strip + 3:2 pad", width=250)
                        if warn:
                            st.warning(warn)
                        photo_result = (preview, "png" if photo_file.type == "image/png" else "jpg")

        batch_rows.append(
            {
                "error": dup_err,
                "title": title,
                "sections": sections,
                "technical_sections": technical_sections,
                "card_id": card_id,
                "order": resolved_order,
                "photo_result": photo_result,
                "lay_ref": f"{title}/{lay_path.name}",
                "technical_ref": f"{title}/{technical_path.name}" if technical_path else "",
            }
        )

valid_batch_rows = [r for r in batch_rows if not r["error"]]
if batch_rows:
    st.caption(f"{len(valid_batch_rows)} of {len(batch_rows)} ready to publish.")

if st.button("Publish batch", type="primary", disabled=not valid_batch_rows):
    cards = load_cards()
    publish_files = {}
    added = []
    skipped = []
    for row in valid_batch_rows:
        if any(c["id"] == row["card_id"] for c in cards):
            skipped.append(row["card_id"])
            continue

        photo_ref = None
        if row["photo_result"] is not None:
            img, ext = row["photo_result"]
            photo_ref = save_photo(img, row["card_id"], ext)
            publish_files[f"public{photo_ref}"] = (PHOTOS_DIR / Path(photo_ref).name).read_bytes()

        new_card = order_card(
            {
                "id": row["card_id"],
                "common_name": row["title"],
                "scientific_name": None,
                "family": None,
                "order": row["order"],
                "taxon_rank": DEFAULT_TAXON_RANK,
                "sourcing": DEFAULT_SOURCING,
                "sections": row["sections"],
                "technical_sections": row["technical_sections"],
                "source_report_ref": {
                    "technical": row["technical_ref"],
                    "lay": row["lay_ref"],
                },
                "photo_ref": photo_ref,
                "reviewed_by": None,
                "reviewed_at": None,
            }
        )
        cards.append(new_card)
        added.append(f"{row['title']} ({row['card_id']})")

    for card_id in skipped:
        st.warning(f"Skipped — '{card_id}' already exists (published elsewhere just now).")

    st.session_state.pending_species_dirs = []
    if added:
        save_cards(cards)
        publish_files["src/data/card_index.json"] = serialize_cards(cards)
        ok = do_publish(
            publish_files,
            commit_message="Add cards: " + ", ".join(added),
            pr_title=f"Add {len(added)} card(s): " + ", ".join(added),
            pr_body=(
                "Automated content-only PR from tools/dudu-intake — no version bump "
                f"(see #34/#40/#89). Adds: {', '.join(added)}."
            ),
        )
        st.session_state.batch_message = (
            f"Batch add: {'published' if ok else 'not published'} ({len(added)} card(s))."
        )
    else:
        st.session_state.batch_message = "Nothing to publish — every card already existed."
    st.rerun()

st.divider()
st.subheader("Existing cards")

st.session_state.setdefault("show_existing_cards", False)
if not st.session_state.show_existing_cards:
    if st.button("Show existing cards"):
        st.session_state.show_existing_cards = True
        st.rerun()
else:
    if st.button("Hide existing cards"):
        st.session_state.show_existing_cards = False
        st.rerun()

    selected_for_removal = []
    cards = load_cards()
    known_orders_existing = sorted({c["order"] for c in cards if c["order"]})
    if not cards:
        st.info("No cards yet.")
    for card in cards:
        if st.checkbox("Select for deletion", key=f"select_delete_{card['id']}"):
            selected_for_removal.append(card)
        with st.expander(f"{card['common_name']} ({card['id']})"):
            left, right = st.columns([1, 2])
            with left:
                if card["photo_ref"]:
                    photo_path = REPO_ROOT / "public" / card["photo_ref"].lstrip("/")
                    if photo_path.exists():
                        st.image(str(photo_path), width=250)
                    else:
                        st.warning(f"photo_ref set but file missing: {card['photo_ref']}")
                else:
                    st.write("No photo yet.")

            with right:
                replacement = st.file_uploader(
                    "Add / replace photo",
                    type=["jpg", "jpeg", "png"],
                    key=f"upload_{card['id']}",
                )
                new_img = None
                if replacement is not None:
                    new_img, warn = process_photo(replacement)
                    st.image(new_img, caption="After metadata strip + 3:2 pad", width=300)
                    if warn:
                        st.warning(warn)

                if card["photo_ref"]:
                    confirm = st.checkbox("Confirm removal", key=f"confirm_{card['id']}")
                    if st.button(
                        "Remove photo", key=f"remove_{card['id']}", disabled=not confirm
                    ):
                        old_photo_ref = card["photo_ref"]
                        delete_photo(old_photo_ref)
                        card["photo_ref"] = None
                        save_cards(cards)

                        do_publish(
                            {
                                "src/data/card_index.json": serialize_cards(cards),
                                f"public{old_photo_ref}": None,
                            },
                            commit_message=f"Remove photo: {card['common_name']} ({card['id']})",
                            pr_title=f"Remove photo: {card['common_name']}",
                            pr_body="Automated content-only PR from tools/dudu-intake — no version bump (see #34).",
                        )

                        st.session_state.existing_card_message = f"Photo removed for {card['common_name']}."
                        st.rerun()

            st.divider()
            st.write("**Update content from a corrected/revised report**")
            content_update = st.file_uploader(
                "Replace lay report",
                type=["pdf"],
                key=f"content_update_{card['id']}",
            )
            new_title, new_sections, content_parse_err = None, None, None
            if content_update is not None:
                new_title, new_sections, content_parse_err = parse_report_pdf(content_update.getvalue())
                if content_parse_err:
                    st.error(content_parse_err)
                else:
                    st.success(f"Parsed '{new_title}' — {len(new_sections)} section(s).")
                    with st.expander("Preview parsed sections"):
                        for s in new_sections:
                            st.markdown(f"**{s['heading']}**")
                            st.write(s["body"])
                    st.caption(
                        f"Keeps id (`{card['id']}`), photo, order, and other metadata unchanged — "
                        "only common_name, sections, technical_sections, and "
                        "source_report_ref.lay/technical are replaced."
                    )

            st.divider()
            st.write("**Order**")
            technical_ref = card["source_report_ref"].get("technical")
            technical_path_existing = None
            if isinstance(technical_ref, str) and technical_ref:
                candidate = DUDUS_ROOT / technical_ref
                technical_path_existing = candidate if candidate.exists() else None
            order_default = card["order"] or guess_order_from_technical(technical_path_existing)
            new_order = order_picker(f"existing_{card['id']}", known_orders_existing, order_default)

            st.divider()
            update_blocked = bool(content_update is not None and content_parse_err)
            if update_blocked:
                st.error("Fix or remove the lay report above before updating.")
            if st.button("Update", key=f"update_{card['id']}", type="primary", disabled=update_blocked):
                changes = []
                publish_files = {}

                if replacement is not None:
                    old_photo_ref = card["photo_ref"]
                    delete_photo(old_photo_ref)
                    ext = "png" if replacement.type == "image/png" else "jpg"
                    card["photo_ref"] = save_photo(new_img, card["id"], ext)
                    publish_files[f"public{card['photo_ref']}"] = (
                        PHOTOS_DIR / Path(card["photo_ref"]).name
                    ).read_bytes()
                    if old_photo_ref and old_photo_ref != card["photo_ref"]:
                        publish_files[f"public{old_photo_ref}"] = None
                    changes.append("photo")

                if content_update is not None and not content_parse_err:
                    card["common_name"] = new_title
                    card["sections"] = new_sections
                    new_technical_path = find_technical_pdf_path(new_title, content_update.name)
                    new_technical_sections = []
                    if new_technical_path is not None:
                        _tech_title, new_technical_sections, tech_err = parse_report_pdf(
                            new_technical_path.read_bytes()
                        )
                        if tech_err:
                            st.warning(
                                f"Technical report didn't parse ({tech_err}) — the "
                                "technical-report link will be removed for this card."
                            )
                            new_technical_sections = []
                    card["technical_sections"] = new_technical_sections
                    card["source_report_ref"] = {
                        "technical": find_technical_ref(new_title, content_update.name),
                        "lay": f"{new_title}/{content_update.name}",
                    }
                    # The old review no longer describes this content — stale until re-reviewed.
                    card["reviewed_by"] = None
                    card["reviewed_at"] = None
                    changes.append("content")

                if new_order != card["order"]:
                    card["order"] = new_order
                    changes.append("order")

                if not changes:
                    st.warning("Nothing to update — upload a photo/report or change the order first.")
                else:
                    save_cards(cards)
                    publish_files["src/data/card_index.json"] = serialize_cards(cards)
                    do_publish(
                        publish_files,
                        commit_message=(
                            f"Update card: {card['common_name']} ({card['id']}) — "
                            + ", ".join(changes)
                        ),
                        pr_title=f"Update card: {card['common_name']}",
                        pr_body=(
                            "Automated content-only PR from tools/dudu-intake — no version bump "
                            f"(see #34/#52). Updated: {', '.join(changes)}."
                        ),
                    )
                    st.session_state.existing_card_message = (
                        f"Updated {', '.join(changes)} for {card['common_name']}."
                    )
                    st.rerun()

            st.divider()
            confirm_delete = st.checkbox(
                "Confirm deletion — removes this card and its photo file",
                key=f"confirm_delete_{card['id']}",
            )
            if st.button(
                "Delete card permanently",
                key=f"delete_{card['id']}",
                disabled=not confirm_delete,
            ):
                old_photo_ref = card["photo_ref"]
                delete_photo(old_photo_ref)
                remaining = [c for c in cards if c["id"] != card["id"]]
                save_cards(remaining)

                publish_files = {"src/data/card_index.json": serialize_cards(remaining)}
                if old_photo_ref:
                    publish_files[f"public{old_photo_ref}"] = None
                do_publish(
                    publish_files,
                    commit_message=f"Delete card: {card['common_name']} ({card['id']})",
                    pr_title=f"Delete card: {card['common_name']}",
                    pr_body="Automated content-only PR from tools/dudu-intake — no version bump (see #34).",
                )

                st.session_state.existing_card_message = (
                    f"Deleted '{card['common_name']}' ({card['id']})."
                )
                st.rerun()


    if selected_for_removal:
        st.divider()
        st.caption("The whole selection publishes as a single PR, same tradeoff as adding.")
        confirm_batch_delete = st.checkbox(
            f"Confirm deletion of {len(selected_for_removal)} card(s) and their photos",
            key="confirm_batch_delete",
        )
        if st.button("Delete selected cards", disabled=not confirm_batch_delete):
            cards = load_cards()
            publish_files = {}
            removed = []
            selected_ids = {c["id"] for c in selected_for_removal}
            for target in selected_for_removal:
                card = next((c for c in cards if c["id"] == target["id"]), None)
                if card is None:
                    st.warning(f"Skipped — '{target['id']}' no longer exists (removed elsewhere just now).")
                    continue
                if card["photo_ref"]:
                    delete_photo(card["photo_ref"])
                    publish_files[f"public{card['photo_ref']}"] = None
                removed.append(f"{card['common_name']} ({card['id']})")

            if removed:
                remaining = [c for c in cards if c["id"] not in selected_ids]
                save_cards(remaining)
                publish_files["src/data/card_index.json"] = serialize_cards(remaining)
                ok = do_publish(
                    publish_files,
                    commit_message="Delete cards: " + ", ".join(removed),
                    pr_title=f"Delete {len(removed)} card(s): " + ", ".join(removed),
                    pr_body=(
                        "Automated content-only PR from tools/dudu-intake — no version bump "
                        f"(see #34/#40). Removes: {', '.join(removed)}."
                    ),
                )
                st.session_state.batch_message = (
                    f"Batch delete: {'published' if ok else 'not published'} ({len(removed)} card(s))."
                )
            else:
                st.session_state.batch_message = "Nothing to publish — no selected card still existed."
            st.rerun()
